import { BookOpen, CircleDot, MessageSquare, UserRoundCheck } from "lucide-react";
import { getCourses, getThreads, getTutorApplications } from "@/lib/data";
import { Badge } from "@/components/ui/badge";
import { LinkButton } from "@/components/ui/link-button";

export default async function AdminPage() {
  const [courses, tutors, threads] = await Promise.all([getCourses(true), getTutorApplications(), getThreads()]);
  const stats = [{ label: "전체 수업", value: courses.length, icon: BookOpen, color: "blue" }, { label: "심사 대기 튜터", value: tutors.filter((t) => t.status === "PENDING").length, icon: UserRoundCheck, color: "amber" }, { label: "진행 중 문의", value: threads.filter((t) => t.status === "OPEN").length, icon: MessageSquare, color: "green" }];
  return <><div className="flex items-end justify-between"><div><p className="text-sm font-bold text-blue-600">ADMIN</p><h1 className="mt-2 text-3xl font-black">운영 대시보드</h1><p className="mt-2 text-sm text-slate-500">서비스의 주요 운영 현황을 확인하세요.</p></div><Badge tone="green"><CircleDot className="mr-1 size-3" />정상 운영 중</Badge></div><div className="mt-8 grid gap-5 md:grid-cols-3">{stats.map(({ label, value, icon: Icon, color }) => <div key={label} className="rounded-2xl border bg-white p-6 shadow-soft"><div className="flex items-center justify-between"><p className="text-sm font-semibold text-slate-500">{label}</p><div className={`grid size-9 place-items-center rounded-xl ${color === "blue" ? "bg-blue-50 text-blue-700" : color === "amber" ? "bg-amber-50 text-amber-700" : "bg-emerald-50 text-emerald-700"}`}><Icon className="size-4" /></div></div><p className="mt-4 text-3xl font-black text-navy-950">{value}</p></div>)}</div><div className="mt-7 grid gap-5 md:grid-cols-2"><div className="rounded-2xl border bg-white p-6"><h2 className="text-lg font-extrabold">빠른 작업</h2><div className="mt-5 flex flex-wrap gap-3"><LinkButton href="/admin/courses/new" size="sm">새 수업 등록</LinkButton><LinkButton href="/admin/tutors" variant="outline" size="sm">튜터 심사</LinkButton><LinkButton href="/admin/messages" variant="outline" size="sm">문의 답변</LinkButton></div></div><div className="rounded-2xl border bg-navy-950 p-6 text-white"><h2 className="text-lg font-extrabold text-white">보안 알림</h2><p className="mt-3 text-sm leading-6 text-slate-300">튜터 증명서는 관리자 전용 임시 링크로만 열람되며, 링크는 60초 후 만료됩니다.</p></div></div></>;
}
